import React from 'react';
import { useLocation, Navigate } from 'react-router-dom';
import { CheckCircle, XCircle, BarChart3 } from 'lucide-react';

export default function Dashboard() {
  const location = useLocation();
  const result = location.state?.result;

  if (!result) {
    return <Navigate to="/" replace />;
  }

  const { scores, overallScore, passFailRecommendation, evidence, summary } = result;
  
  const isPass = passFailRecommendation === 'Pass';

  return (
    <div className="min-h-screen bg-amber-50 p-8 text-gray-800 font-sans">
      <div className="max-w-5xl mx-auto space-y-8">
        
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between bg-white p-8 rounded-[2rem] shadow-sm border border-orange-100">
          <div>
            <h1 className="text-3xl font-extrabold tracking-tight text-gray-800">Candidate Evaluation Report</h1>
            <p className="text-gray-500 mt-2">Generated by AI Tutor Screener</p>
          </div>
          <div className="mt-6 md:mt-0 flex items-center gap-4">
            <div className="text-right">
              <div className="text-sm text-gray-500 font-medium uppercase tracking-wider">Overall Score</div>
              <div className="text-4xl font-black text-orange-500">{overallScore}<span className="text-2xl text-gray-400">/10</span></div>
            </div>
            <div className={`flex items-center gap-2 px-6 py-3 rounded-full font-bold text-lg ${isPass ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
              {isPass ? <CheckCircle className="w-6 h-6" /> : <XCircle className="w-6 h-6" />}
              {passFailRecommendation}
            </div>
          </div>
        </div>

        {/* Summary */}
        <div className="bg-white p-8 rounded-[2rem] shadow-sm border border-orange-100">
          <div className="flex items-center gap-3 mb-4">
            <BarChart3 className="w-6 h-6 text-orange-500" />
            <h2 className="text-xl font-bold text-gray-800">Assessor Summary</h2>
          </div>
          <p className="text-lg leading-relaxed text-gray-700">{summary}</p>
        </div>

        {/* Detailed Scores */}
        <div className="grid md:grid-cols-2 gap-6">
          {Object.entries(scores).map(([metric, score]) => (
            <div key={metric} className="bg-white p-6 rounded-[1.5rem] shadow-sm border border-orange-100">
              <div className="flex justify-between items-center mb-4">
                <h3 className="text-lg font-bold text-gray-800">{metric}</h3>
                <div className={`px-3 py-1 rounded-full text-sm font-bold ${
                  score >= 8 ? 'bg-green-100 text-green-700' :
                  score >= 5 ? 'bg-amber-100 text-amber-700' :
                  'bg-red-100 text-red-700'
                }`}>
                  {score} / 10
                </div>
              </div>
              <div className="w-full bg-orange-100 rounded-full h-2 mb-4">
                <div className="bg-orange-500 h-2 rounded-full" style={{ width: `${(score / 10) * 100}%` }}></div>
              </div>
              <div className="bg-amber-50 p-4 rounded-[1rem] text-sm text-gray-600 italic border border-orange-100">
                "{evidence[metric]}"
              </div>
            </div>
          ))}
        </div>

      </div>
    </div>
  );
}
